version: "3"
# 도커 컴포즈 버전 3
networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest #gitea pull
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=giteadb:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=password_gitea#_2018
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "1022:22"
     depends_on:
       - giteadb
 
   giteadb:
     image: mariadb:5.5
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=youcan'thackpassword123$%^&*)(
       - MYSQL_USER=git
       - MYSQL_PASSWORD=password_gitea#_2018
       - MYSQL_DATABASE=gitea
     networks:
       - gitea
     volumes:
       - ./mysql:/var/lib/mysql 
